name: build-release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_release:
    runs-on: ubuntu-latest
    name: build_release
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Build
        run: |
          mvn clean package -DskipTests
          echo "artifactPath=$(pwd)/target" >> $GITHUB_ENV
          tag=${GITHUB_REF_NAME}
          echo "tag=$tag" >> $GITHUB_ENV
      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: true
          prerelease: false
          release_name: ${{ env.tag }}
          tag_name: ${{ env.tag }}
          body: packaged by github actions
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.artifactPath }}/ysomap.jar
          asset_name: ysomap.jar
          asset_content_type: application/java-archive